### PR TITLE
1.0.1 - Fix always empty landmark columns

### LINKED ISSUE #12: Is it expected to have fields where all values are null
When reviewing the data in the lite dataset, all of the following fields are null in all records.

* unsplash_photos.ai_primary_landmark_name
* unsplash_photos.ai_primary_landmark_latitude
* unsplash_photos.ai_primary_landmark_longitude
* unsplash_photos.ai_primary_landmark_confidence

If all of these are supposed to be null all the time - It may be useful to drop those columns from the dataset completely. 

Although if these columns do have data in the full dataset it makes sense to have them exist. If this is the case, it may be useful to update the [documentation](https://github.com/unsplash/datasets/blob/master/DOCS.md) to note that these fields are null in the lite dataset and have values in the full dataset.

In any case, just checking to make sure that this is the expected behavior.

### PR DESCRIPTION
**Pull request by TimmyCarbone**
#### Overview

- Closes #12 
- Fix: All landmark columns are `null`
- Fix: Some landmark names showing as empty strings instead of `null`
- Fix: Duplicate entry for one photo in the Full Dataset

#### New release

- Upon merging, create a 1.0.1 tag and release for the dataset.
- `/lite/latest` API link updated to the 1.0.1 dataset.

### CODE REVIEW

**Comment by lukechesser** [comment]
@TimmyCarbone did this just apply to the lite dataset or the full as well?

**Comment by TimmyCarbone** [comment]
@lukechesser This applies to both. I think whatever applies to one dataset should apply to the other, under the same version.

**Comment by lukechesser** [comment]
@TimmyCarbone gotcha, thanks, just wanted to make sure for the changelog 👍

**Comment by mizzbbee8778** [comment]
I'm so new to this. I have an Apple Iphone8 plus and my ex got into my router and is getting in my phones and i don't even connect to my WiFi so how is he getting in? We are not together and he has no access to my phone! He is putting programs in my phone and it's saying my iPhone is a Mac. I'm new to all this and I don't know to reverse what He's done. I don't know how to program and i don't know how to put in codes on my phone. He can track me, he puts in his network and he's created an option on my phone that should not be there. He can block calls and stop my outgoing calls as well! I need help and asking anyone to help even if I have to get a new phone how can I block the WiFi from pulling in my phone (which it's not mine so I can't turn it off) I put a firewall up and tunnel and it's already bkocked over 4K trackers. I think he's using adware and in my history it says Facebook. Net and . Com and I don't get on Facebook because he takes them all from me and twitter and Instagram as well which I don't get on. Please can someone email me and tell me how to try to reverse all this and if it can't be and get another new phone how do I keep him out! He isn't gaining my passwords and every time I change my passwords they reset right after I do it. Please help! I've made police reports I've emailed the fbi about it I've done everything I've been told to do and i get nowhere! So this Is my last option! S/N my webpages when I do searches they get redirected as well!

**Comment by mizzbbee8778** [comment]
When you say datasets what is that and where n how I’m sorry I’m so so new to all this.

**Comment by mizzbbee8778** [comment]
When you say datasets what is that and where n how I’m sorry I’m so so new to all this.

**Comment by mizzbbee8778** [comment]
When you say datasets what is that and where n how I’m sorry I’m so so new to all this.

**Comment by mizzbbee8778** [comment]
When you say datasets what is that and where n how I’m sorry I’m so so new to all this.

**Comment by mizzbbee8778** [comment]
When you say datasets what is that and where n how I’m sorry I’m so so new to all this.

**Comment by Mr1262** [comment]
You shouldn’t say that (sorry)
Thanks for interested in doing it work.

**Pull request merged**
